maj

diff --git a/.github/workflows/packaging_addon.yaml b/.github/workflows/packaging_addon.yaml
--- a/.github/workflows/packaging_addon.yaml
+++ b/.github/workflows/packaging_addon.yaml
@@ -21,23 +21,23 @@ jobs:
           zip -rZ bzip2 io_scene_spm.zip io_scene_spm/
           zip -rZ bzip2 io_artiste.zip io_artiste/
           
-      - name: Delete old releases
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          gh release list --json tagName --jq '.[].tagName' | while read tag; do
-            gh release delete "$tag" --yes --cleanup-tag 2>/dev/null || true
-          done
+      #- name: Delete old releases
+        #env:
+          #GH_TOKEN: ${{ github.token }}
+        #run: |
+          #gh release list --json tagName --jq '.[].tagName' | while read tag; do
+            #gh release delete "$tag" --yes --cleanup-tag 2>/dev/null || true
+          #done
 
-      - name: Rreate Release
+      - name: Create Release
         uses: softprops/action-gh-release@v2
         with:
           files: |
             io_antarctica_scene.zip
             io_scene_spm.zip
-            io_artistezip
+            io_artiste.zip
           tag_name: ${{ github.ref_name }}-${{ github.run_id }}
-          name: Generate SuperTuxKart Tools - ${{ github.run_id }}
+          name: SuperTuxKart Tools - ${{ github.run_id }}
           body: |
             ## Auto-Generate
 
